# This is a basic workflow to help you get started with Actions

name: Main workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Setup Java JDK
      - uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      
      - name: Builds the project
        run: ./gradlew assemble

      - name: Run lint checks
        run: ./gradlew check

      - name: Run unit tests
        run: ./gradlew test

  update_release_draft:
    needs: build
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: workflows/release-drafter-config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}