name: Publish release workflow

on:
  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
          # If we split on '/' and take the 3rd value,
          # we can get the release name.
          run: |
            NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
            echo "New version: ${NEW_VERSION}"
            echo "Github username: ${GITHUB_ACTOR}"
            ./gradlew -Pversion=${NEW_VERSION} publish